/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Frontend',
      collapsed: false,
      items: [
        'frontend/readme',
        'frontend/contributing',
        'frontend/autogenerated',
        'frontend/autogenerated/components',
        'frontend/autogenerated/services',
        'frontend/autogenerated/interfaces',
        'frontend/autogenerated/routes'
      ]
    },
    {
      type: 'category',
      label: 'Backend',
      collapsed: false,
      items: [
        'backend/readme',
        'backend/contributing',
        'backend/reference'
      ]
    },
    {
      type: 'category',
      label: 'API',
      collapsed: false,
      items: ['api/swagger']
    }
  ]
};

module.exports = sidebars;
