/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Руководство',
      collapsed: false,
      items: [
        'guide/index',
        {
          type: 'category',
          label: 'Backend',
          collapsed: false,
          items: [
            {type: 'doc', id: 'guide/backend', label: 'Руководство'},
            {type: 'doc', id: 'backend/index', label: 'Backend-документация'},
            {type: 'doc', id: 'backend/overview', label: 'Описание backend'},
            {type: 'doc', id: 'backend/runbook', label: 'Runbook'},
            {type: 'doc', id: 'backend/testing', label: 'Тестирование'},
            {type: 'doc', id: 'backend/monitoring', label: 'Monitoring'},
            {type: 'doc', id: 'backend/reviewer-guide', label: 'Гайд для проверки'},
            {type: 'doc', id: 'backend/reference', label: 'Backend компоненты'}
          ]
        },
        {
          type: 'category',
          label: 'Frontend',
          collapsed: false,
          items: [
            {type: 'doc', id: 'guide/frontend', label: 'Руководство'},
            {type: 'doc', id: 'frontend/autogenerated', label: 'Фронтенд-документация'},
            {type: 'doc', id: 'frontend/autogenerated/components', label: 'Компоненты'},
            {type: 'doc', id: 'frontend/autogenerated/services', label: 'Сервисы'},
            {type: 'doc', id: 'frontend/autogenerated/interfaces', label: 'Интерфейсы'},
            {type: 'doc', id: 'frontend/autogenerated/routes', label: 'Маршруты'}
          ]
        },
        {
          type: 'category',
          label: 'TG bot',
          collapsed: false,
          items: ['guide/tg-bot']
        }
      ]
    },
    'contribution/index',
    {
      type: 'category',
      label: 'Архитектура',
      collapsed: false,
      items: [
        {type: 'doc', id: 'architecture/backend', label: 'Backend'},
        {type: 'doc', id: 'architecture/frontend', label: 'Frontend'},
        {type: 'doc', id: 'architecture/tg-bot', label: 'TG bot'}
      ]
    },
    {
      type: 'category',
      label: 'API',
      collapsed: false,
      items: ['api/swagger']
    }
  ]
};

module.exports = sidebars;
